# Generated by Django 5.2.1 on 2025-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
