# Generated by Django 5.2.1 on 2025-09-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('specs', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('completed', 'Completed')], default='new', max_length=10)),
                ('stage', models.CharField(choices=[('order_intake', 'Order Intake'), ('quotation', 'Quotation'), ('design', 'Design'), ('printing', 'Printing'), ('approval', 'Approval'), ('delivery', 'Delivery')], default='order_intake', max_length=20)),
                ('delivery_code', models.CharField(blank=True, max_length=6, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField(validators=[MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('finishing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paper_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('machine_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('design_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('products_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_3pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DesignStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_designer', models.CharField(blank=True, max_length=255)),
                ('requirements_files_manifest', models.JSONField(blank=True, default=list)),
                ('design_status', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_stage', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_operator', models.CharField(blank=True, max_length=255)),
                ('print_time', models.DateTimeField(blank=True, null=True)),
                ('batch_info', models.CharField(blank=True, max_length=255)),
                ('print_status', models.CharField(choices=[('Pending', 'Pending'), ('Printing', 'Printing'), ('Printed', 'Printed')], default='Pending', max_length=20)),
                ('qa_checklist', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printing_stage', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_approval_files', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stage', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_photo_path', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stage', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('intake', 'Intake'), ('designer', 'Designer'), ('final', 'Final'), ('rider', 'Rider'), ('approval', 'Approval')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage', 'status'], name='orders_order_stage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='orders_order_order_code_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product_id'], name='orders_orderitem_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['order', 'kind'], name='orders_upload_order_kind_idx'),
        ),
    ]
