# Generated by Django 5.0.7 on 2025-09-10 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=120)),
                ('specs', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='new', max_length=20)),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('quotation', 'Quotation'), ('design', 'Design/Production'), ('printing', 'Printing/QA'), ('approval', 'Client Approval'), ('delivery', 'Delivery')], default='intake', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_approval_files', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_code', models.CharField(blank=True, max_length=6)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('rider_photo_path', models.CharField(blank=True, max_length=500)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_designer', models.CharField(blank=True, max_length=255)),
                ('requirements_files', models.JSONField(blank=True, default=list)),
                ('design_status', models.CharField(blank=True, max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_operator', models.CharField(blank=True, max_length=255)),
                ('print_time', models.DateTimeField(blank=True, null=True)),
                ('batch_info', models.CharField(blank=True, max_length=255)),
                ('print_status', models.CharField(blank=True, max_length=50)),
                ('qa_checklist', models.JSONField(blank=True, default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finishing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paper_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('design_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='orders.order')),
            ],
        ),
    ]
