# Generated by Django 5.0.7 on 2025-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="delivery_status",
            field=models.CharField(default="Dispatched", max_length=20),
        ),
    ]
