# Generated by Django 5.2.1 on 2025-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_stage_72c51f_idx',
            old_name='orders_order_stage_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_order_c_cd5b49_idx',
            old_name='orders_order_order_code_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_order_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orderitem_order_product_idx',
        ),
        migrations.RenameIndex(
            model_name='upload',
            new_name='orders_uplo_order_i_e19425_idx',
            old_name='orders_upload_order_kind_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default='TEMP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
