# Generated by Django 5.2.1 on 2025-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order_stage_status_idx_orders_orde_stage_72c51f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricing_status',
            field=models.CharField(default='Not Priced', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='custom_field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
