# Generated by Django 5.0.7 on 2025-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_trn_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
