# Generated by Django 5.2.1 on 2025-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_quotation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_person',
            field=models.TextField(blank=True, help_text="Sales person who sent this order to production"),
        ),
    ]
