# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_trn_and_sales_person_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design_ready',
            field=models.BooleanField(default=False, help_text='Design status for this product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_need_custom',
            field=models.BooleanField(default=False, help_text='Whether this product needs custom design'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_files_manifest',
            field=models.JSONField(default=list, blank=True, help_text='List of design files for this product'),
        ),
    ]

