version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_orders &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=dev
      - DEBUG=1
      - DATABASE_URL=postgresql+psycopg://crm:crm@db:5432/crm
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - MEDIA_URL=/uploads/
      - MEDIA_ROOT=/app/Backend/media/uploads
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHANNELS_REDIS_URL=redis://redis:6379/1
      - MAX_ATTACHMENT_MB=10
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A crm_backend worker -l info
    environment:
      - DJANGO_SECRET_KEY=dev
      - DEBUG=1
      - DATABASE_URL=postgresql+psycopg://crm:crm@db:5432/crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHANNELS_REDIS_URL=redis://redis:6379/1
      - MAX_ATTACHMENT_MB=10
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A crm_backend beat -l info
    environment:
      - DJANGO_SECRET_KEY=dev
      - DEBUG=1
      - DATABASE_URL=postgresql+psycopg://crm:crm@db:5432/crm
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHANNELS_REDIS_URL=redis://redis:6379/1
      - MAX_ATTACHMENT_MB=10
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Backend/media/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - web

volumes:
  pgdata:

