version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=dev
      - DEBUG=1
      - DATABASE_URL=sqlite:////app/Backend/db.sqlite3
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - MEDIA_URL=/uploads/
      - MEDIA_ROOT=/app/Backend/media/uploads
    volumes:
      - .:/app
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Backend/media/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - web

