# Generated by Django 5.0.7 on 2025-09-27 15:49

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_seed_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='actor_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('DESIGNER', 'Designer'), ('PRODUCTION', 'Production'), ('SYSTEM', 'System')], max_length=16),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='hash',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')]),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='source',
            field=models.CharField(choices=[('API', 'Api'), ('ADMIN_UI', 'Admin Ui'), ('FRONTEND', 'Frontend'), ('WORKER', 'Worker'), ('WEBHOOK', 'Webhook')], max_length=16),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='verb',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('STATUS_CHANGE', 'Status Change'), ('COMMENT', 'Comment'), ('UPLOAD', 'Upload'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CHECKIN', 'Checkin'), ('CHECKOUT', 'Checkout'), ('SCREENSHOT', 'Screenshot'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='role_scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='anonymizationjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anonymizationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='filters_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('CSV', 'Csv'), ('NDJSON', 'Ndjson')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='logingestionkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='action',
            field=models.CharField(choices=[('purge', 'Purge'), ('anonymize', 'Anonymize')], max_length=16),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='drop_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='mask_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='role_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='target_type_filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
