# Generated by Django 5.0.7 on 2025-09-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_screenshot_at', models.DateTimeField(blank=True, null=True)),
                ('productivity', models.FloatField(default=0.0)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('screenshot', 'Screenshot'), ('video', 'Video')], max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='monitoring.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('action', models.CharField(blank=True, max_length=120)),
                ('application', models.CharField(blank=True, max_length=120)),
                ('delta_k', models.IntegerField(default=0)),
                ('delta_c', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='monitoring.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'when'], name='monitoring__employe_4a7437_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('keystrokes', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('active_minutes', models.IntegerField(default=0)),
                ('idle_minutes', models.IntegerField(default=0)),
                ('productivity', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='monitoring.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
