# Generated by Django 5.2.1 on 2025-09-25 14:11

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_org_id, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('retention_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_device_id, max_length=25, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=100)),
                ('agent_version', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('IDLE', 'Idle'), ('PAUSED', 'Paused')], default='OFFLINE', max_length=20)),
                ('screenshot_freq_sec', models.IntegerField(default=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.org')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_screenshot_id, max_length=25, primary_key=True, serialize=False)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('blob_key', models.CharField(max_length=500)),
                ('thumb_key', models.CharField(max_length=500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='monitoring.device')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_session_id, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ALLOWED', 'Allowed'), ('PRECONDITION_FAILED', 'Precondition Failed'), ('BLOCKED', 'Blocked')], default='PRECONDITION_FAILED', max_length=20)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_token_id, max_length=25, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='monitoring.device')),
            ],
            options={
                'indexes': [models.Index(fields=['secret'], name='monitoring__secret_360dfd_idx'), models.Index(fields=['expires_at'], name='monitoring__expires_daf44e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_heartbeat_id, max_length=25, primary_key=True, serialize=False)),
                ('cpu_percent', models.FloatField()),
                ('mem_percent', models.FloatField()),
                ('active_window', models.CharField(blank=True, max_length=500, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='monitoring.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'created_at'], name='monitoring__device__8e6a8b_idx'), models.Index(fields=['created_at'], name='monitoring__created_2ebadb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='monitoring__user_id_2d8a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['org', 'status'], name='monitoring__org_id_a4f32e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_heartbeat'], name='monitoring__last_he_a0bc81_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['device', 'taken_at'], name='monitoring__device__769863_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['taken_at'], name='monitoring__taken_a_ee5a59_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['sha256'], name='monitoring__sha256_5b6fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'created_at'], name='monitoring__user_id_368c44_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='monitoring__status_4f0151_idx'),
        ),
    ]
