# Generated by Django 5.2.1 on 2025-09-25 17:59

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_org_device_screenshot_session_devicetoken_heartbeat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUserBind',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_session_id, max_length=25, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=32)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='current_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_user_role',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_user_bind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user_role_snapshot',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='user_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='user_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='user_role_snapshot',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['current_user'], name='monitoring__current_7f50cd_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['user_id_snapshot'], name='monitoring__user_id_ba36c5_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['user_id_snapshot'], name='monitoring__user_id_facb23_idx'),
        ),
        migrations.AddField(
            model_name='deviceuserbind',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_binds', to='monitoring.device'),
        ),
        migrations.AddField(
            model_name='deviceuserbind',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deviceuserbind',
            index=models.Index(fields=['device', 'bound_at'], name='monitoring__device__7a335e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceuserbind',
            index=models.Index(fields=['user', 'bound_at'], name='monitoring__user_id_ca49b4_idx'),
        ),
    ]
