# Generated by Django 5.2.1 on 2025-09-27 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_deviceuserbind_device_current_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_type', 'start_date'], name='monitoring__report__0714e0_idx'), models.Index(fields=['generated_by', 'generated_at'], name='monitoring__generat_6dec34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('application_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(blank=True, max_length=500)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('keystrokes', models.IntegerField(default=0)),
                ('mouse_clicks', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_usage', to='monitoring.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'date'], name='monitoring__device__d48d6e_idx'), models.Index(fields=['user', 'date'], name='monitoring__user_id_19bfb6_idx'), models.Index(fields=['application_name', 'date'], name='monitoring__applica_20b1d7_idx')],
                'unique_together': {('device', 'date', 'application_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductivityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_productivity', 'Low Productivity'), ('high_idle_time', 'High Idle Time'), ('unusual_activity', 'Unusual Activity'), ('application_abuse', 'Application Abuse'), ('offline_device', 'Offline Device')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alert_data', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_alerts', to='monitoring.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'created_at'], name='monitoring__device__5752bd_idx'), models.Index(fields=['user', 'created_at'], name='monitoring__user_id_39cc25_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='monitoring__alert_t_7a9c3c_idx'), models.Index(fields=['severity', 'is_resolved'], name='monitoring__severit_69e3ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_keystrokes', models.IntegerField(default=0)),
                ('total_mouse_clicks', models.IntegerField(default=0)),
                ('total_scroll_events', models.IntegerField(default=0)),
                ('active_time', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('locked_time', models.IntegerField(default=0)),
                ('applications_used', models.JSONField(default=list)),
                ('primary_application', models.CharField(blank=True, max_length=255)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('screenshots_taken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to='monitoring.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'date'], name='monitoring__device__f5c3a7_idx'), models.Index(fields=['user', 'date'], name='monitoring__user_id_44b252_idx'), models.Index(fields=['date'], name='monitoring__date_3a2101_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('total_keystrokes', models.IntegerField(default=0)),
                ('total_mouse_clicks', models.IntegerField(default=0)),
                ('total_scroll_events', models.IntegerField(default=0)),
                ('applications_used', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='monitoring.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'session_start'], name='monitoring__device__9d4db9_idx'), models.Index(fields=['user', 'session_start'], name='monitoring__user_id_5ec272_idx'), models.Index(fields=['is_active'], name='monitoring__is_acti_2f06d7_idx')],
            },
        ),
    ]
