# Generated by Django 5.2.1 on 2025-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_analyticsreport_applicationusage_productivityalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='activity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='idle_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='is_idle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='keystroke_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='keystrokes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='mouse_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='productivity_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='productivity_status',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='scroll_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='active_window_snapshot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
