# Generated by Django 5.2.1 on 2025-09-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_add_device_fields'),
    ]

    operations = [
    ]
