# Generated by Django 5.0.7 on 2025-09-17 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start", models.TimeField(default=datetime.time(9, 0))),
                ("work_end", models.TimeField(default=datetime.time(17, 30))),
                ("grace_minutes", models.PositiveIntegerField(default=5)),
                ("standard_work_minutes", models.PositiveIntegerField(default=510)),
                ("overtime_after_minutes", models.PositiveIntegerField(default=510)),
                (
                    "late_penalty_per_minute",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "per_day_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "overtime_rate_per_minute",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("weekend_days", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance rule",
                "verbose_name_plural": "Attendance rules",
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="device_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                ],
                default="present",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="total_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
