# Generated by Django 5.0.7 on 2025-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancerule_attendance_device_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
