# Generated by Django 5.0.7 on 2025-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
